# Generated by Django 5.0 on 2024-09-11 18:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_img', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='up_img',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
