# Generated by Django 5.0 on 2024-09-11 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_img', '0002_up_img_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='up_img',
            name='time',
        ),
    ]
