# Generated by Django 5.0 on 2024-09-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_img', '0003_remove_up_img_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='up_img',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
